version: '3.4'

services:
  api:
    image: parla-api
    platform:  linux/arm64/v8
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      SUPABASE_URL: "${SUPABASE_URL}"
      SUPABASE_ANON_KEY: "${SUPABASE_ANON_KEY}"
      OPENAI_KEY: "${OPENAI_KEY}"
      OPENAI_MODEL: "${OPENAI_MODEL}"

    ports:
      - 8080:8080
