create extension if not exists "vector" with schema "extensions";

CREATE TABLE public.registered_documents(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_url text not null,
    source_type text not null,
    registered_at timestamp not null,
    metadata jsonb
);

CREATE TABLE public.processed_documents(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_checksum text not null,
    file_size integer not null,
    num_pages integer not null,
    processing_started_at timestamp,
    processing_finished_at timestamp,
    processing_error text,
    registered_document_id integer REFERENCES public.registered_documents(id) ON DELETE CASCADE
);

CREATE TABLE public.processed_document_summaries(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    summary text not null,
    summary_embedding vector(1536) not null,
    tags text [] not null,
    processed_document_id integer REFERENCES public.processed_documents(id) ON DELETE CASCADE
);

CREATE TABLE public.processed_document_chunks(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content text not null,
    embedding vector(1536) not null,
    page integer not null,
    chunk_index integer not null,
    processed_document_id integer REFERENCES public.processed_documents(id) ON DELETE CASCADE
);