# This workflow will do a clean install of node dependencies, build the source code and run tests
name: Node.js CI
permissions:
  contents: write
  packages: write
on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

jobs:
  build:
    env:
      CI: true
      # This is production environment variables
      SUPABASE_URL: http://localhost:54321
      SUPABASE_SERVICE_ROLE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
      OPENAI_KEY: sk-abc...
      OPENAI_MODEL: gpt-4o-mini
      NODE_ENV: test
      LOG_LEVEL: error
      DANGEROUSLY_ALLOW_CORS_FOR_ALL_ORIGINS: FOR_REAL_REAL

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - uses: supabase/setup-cli@v1
        with:
          version: 1.115.4
      - run: supabase start
      - run: npm ci
      - name: lint
        run: npm run lint
      # - name: prettier
      #   run: npm run prettier:ci
      - run: npm run build --if-present
      - run: npm run test  --if-present
      - run: supabase stop
  release:
    name: semantic-release
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - run: |
          npm ci
          npx semantic-release --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
